# -*- coding: utf-8 -*-
"""
Created on Mon Apr 12 20:50:23 2021

@author: nikla
"""

import time

X = int(input("How many times do you want to loop it?"))
for i in range(X) :

    print("Work it,")
    time.sleep(1)
    print("Make it,")
    time.sleep(1)
    print("Do it,")
    time.sleep(1)
    print("Makes us.")
    time.sleep(1)
    print("Harder,")
    time.sleep(1)
    print("Better,")
    time.sleep(1)
    print("Faster,")
    time.sleep(1)
    print("Stronger.")
    time.sleep(1)
    print("More than,")
    time.sleep(1)
    print("Hour,")
    time.sleep(1)
    print("Never.")
    time.sleep(1)
    print("Ever,")
    time.sleep(1)
    print("After,")
    time.sleep(1)
    print("Work is,")
    time.sleep(1)
    print("Over.")
    
    "Refrain"
    time.sleep(0.9)
    print("Work it Harder")
    time.sleep(0.9)
    print("Make it Better")
    time.sleep(0.9)
    print("Do it Faster")
    time.sleep(0.9)
    print("Makes us Stronger.")
    time.sleep(0.9)
    print("More than Ever")
    time.sleep(0.9)
    print("Hour After")
    time.sleep(0.9)
    print("Our Work is")
    time.sleep(0.9)
    print("Never Over.")
    time.sleep(0.9)
    print("Work it Harder")
    time.sleep(0.9)
    print("Make it Better")
    time.sleep(0.9)
    print("Do it Faster")
    time.sleep(0.9)
    print("Makes us Stronger")
    time.sleep(0.9)
    print("Work it Harder, Make it Better")
    
    "Here start the new stuff"
    time.sleep(0.8)
    print("Do it Faster, Makes us Stronger")
    time.sleep(0.8)
    print("More than Ever, Hour After")
    time.sleep(0.8)
    print("Our Work is Never Over.")
    time.sleep(0.8)
    print("Work it Harder, Make it Better")
    time.sleep(0.8)
    print("Do it Faster, Makes us Stronger")
    time.sleep(0.8)
    print("More than Ever, Hour After")
    time.sleep(0.8)
    print("Our Work is Never Over.")
    time.sleep(0.8)
    print("Work it Harder, Make it Better")
    time.sleep(0.8)
    print("Do it Faster, Makes us Stronger")
    time.sleep(0.8)
    print("More than Ever, Hour AfterOur Work is")
    time.sleep(0.8)
    print("Never Over.")
    time.sleep(0.8)
    print("Work it Harder")
    time.sleep(0.8)
    print("Make it Better")
    time.sleep(0.8)
    print("Do it Faster")
    time.sleep(0.8)
    print("Makes us Stronger")
    time.sleep(0.8)
    print("More than Ever")
    time.sleep(0.8)
    print("Make it Better")
    time.sleep(0.8)
    print("Do it Faster")
    time.sleep(0.8)
    print("Makes us Stronger.")
    time.sleep(0.8)
    print("More than Ever")
    time.sleep(0.8)
    print("Hour After")
    time.sleep(0.8)
    print("Our Work is")
    time.sleep(0.8)
    print("Never Over.")
   
    "refrain"
    print("Work it Harder")
    time.sleep(0.7)
    print("Make it Better")
    time.sleep(0.7)
    print("Do it Faster")
    time.sleep(0.7)
    print("Makes us Stronger.")
    time.sleep(0.7)
    print("More than Ever")
    time.sleep(0.7)
    print("Hour After")
    time.sleep(0.7)
    print("Our Work is")
    time.sleep(0.7)
    print("Never Over.")
    time.sleep(0.7)
    print("Work it Harder")
    time.sleep(0.7)
    print("Make it Better")
    time.sleep(0.7)
    print("Do it Faster")
    time.sleep(0.7)
    print("Makes us Stronger")
    time.sleep(0.7)
    print("Work it Harder, Make it Better")
    
    "final refrain"
    print("Work it Harder")
    time.sleep(0.5)
    print("(Make it Better)")
    time.sleep(0.5)
    print("Do it Faster")
    time.sleep(0.5)
    print("(Makes us Stronger)")
    time.sleep(0.5)
    print("More than Ever")
    time.sleep(0.5)
    print("(Hour After)")
    time.sleep(0.5)
    print("Our Work is")
    time.sleep(0.5)
    print("Never Over.")
    time.sleep(0.5)
    print("Work it Harder")
    time.sleep(0.5)
    print("Make it Better")
    time.sleep(0.5)
    print("Do it Faster")
    time.sleep(0.5)
    print("Makes us Stronger")
    time.sleep(0.5)
    print("More than Ever")
    time.sleep(0.5)
    print("Hour After")
    time.sleep(0.5)
    print("Never Over.")

